let heroes=[], rarity="All", role="All", season="All", current=null;
const grid=document.querySelector('#grid'), count=document.querySelector('#count');
fetch('hero-manifest.json').then(r=>r.json()).then(d=>{heroes=d;document.querySelector('#heroTotal').textContent=d.length;render()});
const rank=r=>r.startsWith('SSR')?3:r==='SR'?2:1;
function render(){
 const q=document.querySelector('#search').value.toLowerCase().trim();
 let list=heroes.filter(h=>{
  const ro=rarity==='All'||(rarity==='SSR'&&h.rarity.startsWith('SSR'))||h.rarity===rarity;
  return ro&&(role==='All'||h.type===role)&&(season==='All'||h.season===season)&&h.name.toLowerCase().includes(q)
 });
 if(document.querySelector('#sort').value==='name') list.sort((a,b)=>a.name.localeCompare(b.name)); else list.sort((a,b)=>rank(b.rarity)-rank(a.rarity)||a.name.localeCompare(b.name));
 count.textContent=`${list.length} heroes`;
 grid.innerHTML=list.map(h=>`<article class="card" data-id="${h.id}"><div class="portrait"><img src="${h.image}" alt="${h.name}"><div class="type-dot">${h.type==='Shield'?'🛡':h.type==='Shooter'?'⚔':'◈'}</div></div><div class="card-body"><span class="pill ${h.rarity==='SR'?'sr':h.rarity==='R'?'r':''}">${h.rarity}</span><h3>${h.name}</h3><p>${h.type} · ${h.season}</p></div></article>`).join('');
 document.querySelectorAll('.card').forEach(c=>c.onclick=()=>openHero(c.dataset.id));
}
async function getHero(id){const h=heroes.find(x=>x.id===id); return await fetch(h.data).then(r=>r.json())}
async function openHero(id){current=await getHero(id); renderDetail(current); document.querySelector('#modal').classList.remove('hidden')}
function levels(a=[]){return `<div class="levels">${a.map((v,i)=>`<span class="${v?'filled':''}">Lv.${i+1}</span>`).join('')}</div>`}
function skill(s){return `<article class="skill-card"><div class="skill-icon">${s.icon?`<img src="${s.icon}" alt="">`:'✦'}</div><div class="skill-copy"><h4>${s.name||'Skill'}</h4><p>${s.description||'Add description.'}</p>${levels(s.levels)}</div></article>`}
function sec(title,arr){return `<section class="detail-section"><div class="detail-title"><span></span><h3>${title}</h3></div><div class="skills-grid">${(arr||[]).map(skill).join('')}</div></section>`}
function list(arr){return arr&&arr.length?`<ul>${arr.map(x=>`<li>${x}</li>`).join('')}</ul>`:'<p class="muted">Not added yet.</p>'}
function renderDetail(h){
 const s=h.stats||{}; const r=h.rating||{};
 document.querySelector('#modalContent').innerHTML=`<div class="hero-detail"><div class="detail-head"><div class="detail-portrait"><img src="${h.image}" alt="${h.name}"></div><div class="detail-main"><div class="detail-top"><div><span class="pill">${h.rarity}</span>${h.tier?`<span class="tier-badge">Tier ${h.tier}</span>`:''}</div><div class="actions"><button class="share-btn" onclick="shareHero()">↗ Share</button><button class="edit-btn" onclick="editHero()">✎ Edit</button></div></div><h2>${h.name}</h2><p class="detail-sub">${h.subtitle||''}</p><div class="detail-meta">${h.type} &nbsp;|&nbsp; ${h.season} ${h.tags?.length?' | '+h.tags.join(' · '):''}</div></div></div>
 <section class="detail-section"><div class="detail-title"><span></span><h3>Stats</h3></div><div class="stats-grid">${[['Arrest ATK',s.arrestAtk],['Arrest DEF',s.arrestDef],['Arrest HP',s.arrestHp],['War ATK/DEF',s.warAtkDef]].map(x=>`<div class="stat"><small>${x[0]}</small><b>${x[1]||'—'}</b></div>`).join('')}</div></section>
 <section class="detail-section"><div class="detail-title"><span></span><h3>My Ratings</h3></div><div class="rating-grid">${[['Overall',r.overall],['Rally',r.rally],['Defense',r.defense],['Arena',r.arena],['Value',r.value]].map(x=>`<div class="rating"><small>${x[0]}</small><strong>${x[1]||'—'}</strong></div>`).join('')}</div></section>
 ${sec('Arrest Skills',h.arrestSkills)}${sec('War Skills',h.warSkills)}${sec('Exclusive Equipment',h.exclusiveEquipment)}
 <section class="detail-section"><div class="detail-title"><span></span><h3>Strategy Guide</h3></div><div class="strategy-grid"><div><small>Rally Use</small><p>${h.rallyUse||'Add your rally guide here.'}</p></div><div><small>Defense Use</small><p>${h.defenseUse||'Add your defense guide here.'}</p></div><div><small>Best Partners</small>${list(h.bestPartners)}</div><div><small>Recommended Teams</small>${list(h.recommendedTeams)}</div><div><small>Counter Heroes</small>${list(h.counterHeroes)}</div><div><small>War Skill Tags</small>${list(h.warSkillTags)}</div><div class="wide"><small>Strategy Notes</small><p>${h.strategy||'Add your strategy notes here.'}</p></div><div class="wide"><small>Personal Notes</small><p>${h.notes||'Add your own notes here.'}</p></div></div></section>
 <div class="detail-footer"><button onclick="prevHero()">← Previous</button><button onclick="nextHero()">Next →</button></div></div>`;
}
function editHero(){
 const h=current,r=h.rating||{};
 document.querySelector('#editor').classList.remove('hidden');
 document.querySelector('#editorContent').innerHTML=`<div class="editor-head"><h2>Edit ${h.name}</h2><button class="close-editor" onclick="closeEditor()">×</button></div><div class="form-grid"><label>Tier<input id="e-tier" value="${h.tier||''}"></label><label>Overall<input id="e-overall" value="${r.overall||''}"></label><label>Rally<input id="e-rally" value="${r.rally||''}"></label><label>Defense<input id="e-defense" value="${r.defense||''}"></label><label>Arena<input id="e-arena" value="${r.arena||''}"></label><label>Value<input id="e-value" value="${r.value||''}"></label><label class="wide">Rally Use<textarea id="e-ru">${h.rallyUse||''}</textarea></label><label class="wide">Defense Use<textarea id="e-du">${h.defenseUse||''}</textarea></label><label class="wide">Best Partners (one per line)<textarea id="e-bp">${(h.bestPartners||[]).join('\n')}</textarea></label><label class="wide">Recommended Teams (one per line)<textarea id="e-rt">${(h.recommendedTeams||[]).join('\n')}</textarea></label><label class="wide">Counter Heroes (one per line)<textarea id="e-ch">${(h.counterHeroes||[]).join('\n')}</textarea></label><label class="wide">War Skill Tags (one per line)<textarea id="e-ws">${(h.warSkillTags||[]).join('\n')}</textarea></label><label class="wide">Strategy Notes<textarea id="e-strategy">${h.strategy||''}</textarea></label><label class="wide">Personal Notes<textarea id="e-notes">${h.notes||''}</textarea></label></div><div class="editor-actions"><button onclick="saveLocal()">Save in Browser</button><button onclick="downloadHero()">Download JSON</button></div><p class="editor-hint">Browser kaydı sadece bu cihazda tutulur. GitHub Pages'e kalıcı eklemek için indirilen JSON dosyasını ilgili <b>heroes/</b> dosyasıyla değiştir.</p>`;
}
function val(id){return document.querySelector(id).value.trim()}
function lines(id){return val(id).split('\n').map(x=>x.trim()).filter(Boolean)}
function collect(){const h=structuredClone(current);h.tier=val('#e-tier');h.rating={overall:val('#e-overall'),rally:val('#e-rally'),defense:val('#e-defense'),arena:val('#e-arena'),value:val('#e-value')};h.rallyUse=val('#e-ru');h.defenseUse=val('#e-du');h.bestPartners=lines('#e-bp');h.recommendedTeams=lines('#e-rt');h.counterHeroes=lines('#e-ch');h.warSkillTags=lines('#e-ws');h.strategy=val('#e-strategy');h.notes=val('#e-notes');h.lastUpdated=new Date().toISOString().slice(0,10);return h}
function saveLocal(){current=collect();localStorage.setItem('loj:'+current.id,JSON.stringify(current));renderDetail(current);closeEditor();alert('Saved in this browser.');}
function downloadHero(){const h=collect();const blob=new Blob([JSON.stringify(h,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=h.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'.json';a.click();URL.revokeObjectURL(a.href)}
function closeEditor(){document.querySelector('#editor').classList.add('hidden')}
function shareHero(){if(navigator.share)navigator.share({title:`${current.name} — Lands of Jail`,url:location.href});else navigator.clipboard?.writeText(location.href)}
function move(dir){let i=heroes.findIndex(x=>x.id===current.id);i=(i+dir+heroes.length)%heroes.length;openHero(heroes[i].id)}
function prevHero(){move(-1)} function nextHero(){move(1)}
function active(sel,v){document.querySelectorAll(sel).forEach(b=>b.classList.toggle('active',b.dataset.value===v))}
document.querySelectorAll('#rarityFilters .chip').forEach(b=>b.onclick=()=>{rarity=b.dataset.value;active('#rarityFilters .chip',rarity);render()});document.querySelectorAll('#roleFilters .chip').forEach(b=>b.onclick=()=>{role=b.dataset.value;active('#roleFilters .chip',role);render()});document.querySelector('#season').onchange=e=>{season=e.target.value;render()};document.querySelector('#sort').onchange=render;document.querySelector('#search').oninput=render;document.querySelector('#clear').onclick=()=>{rarity='All';role='All';season='All';document.querySelector('#search').value='';document.querySelector('#season').value='All';active('#rarityFilters .chip','All');active('#roleFilters .chip','All');render()};document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>document.querySelector('#modal').classList.add('hidden'));document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelector('#modal').classList.add('hidden');closeEditor()}});document.querySelector('#themeBtn').onclick=()=>document.body.classList.toggle('light');
