/* =========================================================
   LANDS OF JAIL - ALL PAGES TRANSLATIONS (EN, KO, ZH-TW, DE, TR)
========================================================= */

const translations = {
  // 1. İNGİLİZCE (EN)
  en: {
    hero_database: "Hero Database",
    nav_home: "Home",
    nav_heroes: "Heroes",
    nav_events: "Events",
    footer_text: "Unofficial community database - Server #185 & #197 - el Fuego",
    community_db_title: "Community Database",
    select_section: "Select a section to continue",

    // Kicker & Page Titles
    tome_kicker: "TOME",
    hero_kicker: "HERO",
    equipment_kicker: "EQUIPMENT",
    trove_kicker: "TROVE",

    armor_title: "Prisoner Armor Upgrade Requirements",
    equipment_title: "Equipment Reformation Requirements",
    trove_title: "Trove Collection Upgrade Requirements",
    tome_upgrade_title: "Tome Upgrade Requirements",
    troop_guide_title: "Troop Guide & Combat Mechanics",
    satellite_title: "Satellite Upgrade Requirements",
    hero_equipment_title: "Hero Exclusive Equipment Upgrade Requirements",
    hero_star_title: "Hero Star Upgrade Requirements",

    // Home Cards
    card_cage_title: "Cage Event",
    card_cage_desc: "Cage event information.",
    card_armor_title: "Prisoner Armor",
    card_armor_desc: "Prisoner Armor levelling and core upgrading requirements.",
    card_trove_title: "Trove Upgrade",
    card_trove_desc: "Trove upgrade requirements.",
    card_tome_title: "Tome Upgrade",
    card_tome_desc: "Tome upgrade requirements.",
    card_troop_title: "Troop Guide",
    card_troop_desc: "Troop types, counters and combat mechanics.",
    card_satellite_title: "Satellite",
    card_satellite_desc: "Satellite information and upgrade guide.",
    card_equip_ref_title: "Hero Equipment Reformation",
    card_equip_ref_desc: "Hero Equipment Reformation upgrade requirements.",
    card_hero_equip_title: "Hero Exclusive Equipment",
    card_hero_equip_desc: "Hero exclusive equipment information and requirements.",
    card_hero_star_title: "Hero Star",
    card_hero_star_desc: "Hero star upgrade requirements.",

    // Cage Event Page
    event_guide_eyebrow: "EVENT GUIDE",
    cage_word: "Cage",
    event_word: "Event",
    hero_banner_desc: "Recommended rally starter heroes, joiner heroes, troop ratios and strategy information for the Cage Event!",
    cage_core: "CAGE",
    section_kicker_guide: "EVENT GUIDE",
    cage_event_title: "Cage Event",
    guide_panel_desc: "Select your available heroes below to build custom Cage Rally teams and optimize your troop formations.",
    cage_team_label: "CAGE TEAM",
    rally_starter_team: "Rally Starter Team",
    select_hero: "Select Hero",
    select_hero_upper: "SELECT HERO",
    class_shooter: "SHOOTER",
    class_bomber: "BOMBER",
    class_shield: "SHIELD",
    label_shooter: "Shooter",
    label_bomber: "Bomber",
    label_shield: "Shield",
    troop_formation_title: "TROOP FORMATION",
    power_armor_7: "Power Armor No.07",
    power_armor_5: "Power Armor No.05",
    power_armor_4: "Power Armor No.04",
    stats_max: "STATISTICS(Max)",
    stat_shooter_atk: "Shooter ATK",
    stat_shooter_def: "Shooter DEF",
    stat_bomber_atk: "Bomber ATK",
    robot_note_text: '"Phantom Cat (Power Armor No.07) is currently the most effective Power Armor in the Cage event. Activating more Cores will directly maximize the potential of its Core Skill."',
    cage_event_upper: "CAGE EVENT",
    joiner_heroes_title: "Joiner Heroes (Use one hero of each tier)",
    tier_word: "TIER",
    note_1: "Use only 4-star or higher characters with first war skill Maxed/Level 5",
    note_2: "Adjust the first 4 joiner heroes in yor own rallies.",
    note_3: "Same joiner war skills will not stack.",
    event_strategy_upper: "EVENT STRATEGY",
    strategy_title: "Strategy",
    strategy_desc: "Strategy information will be added here.",
    community_knowledge_upper: "COMMUNITY KNOWLEDGE",
    tips_title: "Tips & Notes",
    tips_desc: "Useful tips, tested formations and community notes will be added here."
  },

  // 2. KORECE (KO)
  ko: {
    hero_database: "영웅 데이터베이스",
    nav_home: "홈",
    nav_heroes: "영웅",
    nav_events: "이벤트",
    footer_text: "비공식 커뮤니티 데이터베이스 - Server #185 & #197 - el Fuego",
    community_db_title: "커뮤니티 데이터베이스",
    select_section: "계속하려면 섹션을 선택하세요",

    tome_kicker: "비급서",
    hero_kicker: "영웅",
    equipment_kicker: "장비",
    trove_kicker: "보물상자",

    armor_title: "죄수 강화복 업그레이드 조건",
    equipment_title: "장비 개조 조건",
    trove_title: "보물상자 수집 업그레이드 조건",
    tome_upgrade_title: "비급서 업그레이드 조건",
    troop_guide_title: "부대 가이드 및 전투 메커니즘",
    satellite_title: "위성 업그레이드 조건",
    hero_equipment_title: "영웅 전용 장비 업그레이드 조건",
    hero_star_title: "영웅 성급 업그레이드 조건",

    card_cage_title: "케이지 이벤트",
    card_cage_desc: "케이지 이벤트 정보.",
    card_armor_title: "죄수 강화복",
    card_armor_desc: "죄수 강화복 레벨업 및 코어 업그레이드 조건.",
    card_trove_title: "보물상자 업그레이드",
    card_trove_desc: "보물상자 업그레이드 조건.",
    card_tome_title: "비급서 업그레이드",
    card_tome_desc: "비급서 업그레이드 조건.",
    card_troop_title: "부대 가이드",
    card_troop_desc: "병종, 상성 및 전투 메커니즘.",
    card_satellite_title: "위성",
    card_satellite_desc: "위성 정보 및 업그레이드 가이드.",
    card_equip_ref_title: "영웅 장비 개조",
    card_equip_ref_desc: "영웅 장비 개조 업그레이드 조건.",
    card_hero_equip_title: "영웅 전용 장비",
    card_hero_equip_desc: "영웅 전용 장비 정보 및 조건.",
    card_hero_star_title: "영웅 성급",
    card_hero_star_desc: "영웅 성급 업그레이드 조건.",

    event_guide_eyebrow: "이벤트 가이드",
    cage_word: "케이지",
    event_word: "이벤트",
    hero_banner_desc: "케이지 이벤트를 위한 추천 랠리 집결 영웅, 참여 영웅, 부대 비율 및 전략 정보입니다!",
    cage_core: "케이지",
    section_kicker_guide: "이벤트 가이드",
    cage_event_title: "케이지 이벤트",
    guide_panel_desc: "아래에서 보유한 영웅을 선택하여 맞춤형 케이지 랠리 팀을 구성하고 부대 배치를 최적화하세요.",
    cage_team_label: "케이지 팀",
    rally_starter_team: "랠리 스타터 팀",
    select_hero: "영웅 선택",
    select_hero_upper: "영웅 선택",
    class_shooter: "슈터",
    class_bomber: "폭파범",
    class_shield: "실드",
    label_shooter: "슈터",
    label_bomber: "폭파범",
    label_shield: "실드",
    troop_formation_title: "부대 배치",
    power_armor_7: "파워 아머 No.07",
    power_armor_5: "파워 아머 No.05",
    power_armor_4: "파워 아머 No.04",
    stats_max: "스탯 (최대)",
    stat_shooter_atk: "슈터 공격력",
    stat_shooter_def: "슈터 방어력",
    stat_bomber_atk: "폭파범 공격력",
    robot_note_text: '"팬텀 캣 (Power Armor No.07)은 현재 케이지 이벤트에서 가장 효과적인 파워 아머입니다. 더 많은 코어를 활성화하면 코어 스킬의 잠재력을 최대한 끌어올릴 수 있습니다."',
    cage_event_upper: "케이지 이벤트",
    joiner_heroes_title: "참여 영웅 (티어당 1명의 영웅 사용)",
    tier_word: "티어",
    note_1: "첫 번째 전쟁 스킬이 마스터/레벨 5인 4성 이상의 캐릭터만 사용하세요.",
    note_2: "자신의 랠리에서 처음 4명의 참여 영웅을 조정하세요.",
    note_3: "동일한 참여 영웅 전쟁 스킬은 중복 적용되지 않습니다.",
    event_strategy_upper: "이벤트 전략",
    strategy_title: "전략",
    strategy_desc: "전략 정보가 여기에 추가될 예정입니다.",
    community_knowledge_upper: "커뮤니티 지식",
    tips_title: "팁 및 참고사항",
    tips_desc: "유용한 팁, 검증된 조합 및 커뮤니티 메모가 여기에 추가될 예정입니다."
  },

  // 3. GELENEKSEL ÇİNCE (ZH-TW)
  "zh-TW": {
    hero_database: "英雄資料庫",
    nav_home: "首頁",
    nav_heroes: "英雄",
    nav_events: "活動",
    footer_text: "非官方社群資料庫 - Server #185 & #197 - el Fuego",
    community_db_title: "社群資料庫",
    select_section: "請選擇項目以繼續",

    tome_kicker: "典籍",
    hero_kicker: "英雄",
    equipment_kicker: "裝備",
    trove_kicker: "寶庫",

    armor_title: "囚徒裝甲升級需求",
    equipment_title: "裝備改造需求",
    trove_title: "寶庫收藏升級需求",
    tome_upgrade_title: "典籍升級需求",
    troop_guide_title: "部隊指南與戰鬥機制",
    satellite_title: "衛星升級需求",
    hero_equipment_title: "英雄專屬裝備升級需求",
    hero_star_title: "英雄星級升級需求",

    card_cage_title: "鳥籠活動",
    card_cage_desc: "鳥籠活動相關資訊。",
    card_armor_title: "囚徒裝甲",
    card_armor_desc: "囚徒裝甲升級與核心強化需求。",
    card_trove_title: "寶庫升級",
    card_trove_desc: "寶庫升級需求。",
    card_tome_title: "典籍升級",
    card_tome_desc: "典籍升級需求。",
    card_troop_title: "部隊指南",
    card_troop_desc: "兵種類型、相剋關係與戰鬥機制。",
    card_satellite_title: "衛星",
    card_satellite_desc: "衛星資訊與升級指南。",
    card_equip_ref_title: "英雄裝備改造",
    card_equip_ref_desc: "英雄裝備改造升級需求。",
    card_hero_equip_title: "英雄專屬裝備",
    card_hero_equip_desc: "英雄專屬裝備資訊與需求。",
    card_hero_star_title: "英雄星級",
    card_hero_star_desc: "英雄星級升級需求。",

    event_guide_eyebrow: "活動指南",
    cage_word: "鳥籠",
    event_word: "活動",
    hero_banner_desc: "鳥籠活動推薦集結發起英雄、跟隊英雄、兵種比例與戰術策略！",
    cage_core: "鳥籠",
    section_kicker_guide: "活動指南",
    cage_event_title: "鳥籠活動",
    guide_panel_desc: "在下方選擇您擁有的英雄，組建自訂鳥籠集結隊伍並最佳化部隊配置。",
    cage_team_label: "鳥籠隊伍",
    rally_starter_team: "集結發起隊伍",
    select_hero: "選擇英雄",
    select_hero_upper: "選擇英雄",
    class_shooter: "射手",
    class_bomber: "爆破手",
    class_shield: "護盾",
    label_shooter: "射手",
    label_bomber: "爆破手",
    label_shield: "護盾",
    troop_formation_title: "部隊配置",
    power_armor_7: "動力裝甲 07 號",
    power_armor_5: "動力裝甲 05 號",
    power_armor_4: "動力裝甲 04 號",
    stats_max: "數據統計(最大值)",
    stat_shooter_atk: "射手攻擊力",
    stat_shooter_def: "射手防禦力",
    stat_bomber_atk: "爆破手攻擊力",
    robot_note_text: '"幻影貓 (動力裝甲 07 號) 是目前鳥籠活動中最高效的動力裝甲。解鎖更多核心將直接發揮其核心技能的最大潛能。"',
    cage_event_upper: "鳥籠活動",
    joiner_heroes_title: "跟隊英雄 (每個階級使用一名英雄)",
    tier_word: "階級",
    note_1: "僅使用首個戰爭技能滿級/5級的 4 星或以上角色",
    note_2: "請在您發起的集結中調整前 4 名跟隊英雄。",
    note_3: "相同的跟隊英雄戰爭技能效果無法疊加。",
    event_strategy_upper: "活動策略",
    strategy_title: "策略",
    strategy_desc: "策略相關資訊將於此處更新。",
    community_knowledge_upper: "社群知識",
    tips_title: "提示與注意事項",
    tips_desc: "實用技巧、經測試的隊伍配置與社群筆記將於此處更新。"
  },

  // 4. ALMANCA (DE)
  de: {
    hero_database: "Helden-Datenbank",
    nav_home: "Startseite",
    nav_heroes: "Helden",
    nav_events: "Events",
    footer_text: "Inoffizielle Community-Datenbank - Server #185 & #197 - el Fuego",
    community_db_title: "Community-Datenbank",
    select_section: "Wählen Sie einen Bereich, um fortzufahren",

    tome_kicker: "BUCH",
    hero_kicker: "HELD",
    equipment_kicker: "AUSRÜSTUNG",
    trove_kicker: "SCHATZKAMMER",

    armor_title: "Gefangenen-Rüstung Upgrade-Anforderungen",
    equipment_title: "Ausrüstungs-Reformierung Anforderungen",
    trove_title: "Schatzkammer-Sammlung Upgrade-Anforderungen",
    tome_upgrade_title: "Buch-Upgrade Anforderungen",
    troop_guide_title: "Truppen-Guide & Kampfmechaniken",
    satellite_title: "Satelliten-Upgrade Anforderungen",
    hero_equipment_title: "Exklusive Heldenausrüstung Upgrade-Anforderungen",
    hero_star_title: "Helden-Stern Upgrade-Anforderungen",

    card_cage_title: "Käfig-Event",
    card_cage_desc: "Informationen zum Käfig-Event.",
    card_armor_title: "Gefangenen-Rüstung",
    card_armor_desc: "Anforderungen für Rüstungs-Level und Kern-Upgrades.",
    card_trove_title: "Schatzkammer-Upgrade",
    card_trove_desc: "Anforderungen für Schatzkammer-Upgrades.",
    card_tome_title: "Buch-Upgrade",
    card_tome_desc: "Anforderungen für Buch-Upgrades.",
    card_troop_title: "Truppen-Guide",
    card_troop_desc: "Truppentypen, Konter und Kampfmechaniken.",
    card_satellite_title: "Satellit",
    card_satellite_desc: "Satelliten-Informationen und Upgrade-Guide.",
    card_equip_ref_title: "Heldenausrüstung-Reformierung",
    card_equip_ref_desc: "Anforderungen für Ausrüstungs-Reformierung.",
    card_hero_equip_title: "Exklusive Heldenausrüstung",
    card_hero_equip_desc: "Informationen und Anforderungen für exklusive Heldenausrüstung.",
    card_hero_star_title: "Helden-Sterne",
    card_hero_star_desc: "Anforderungen für Helden-Stern-Upgrades.",

    event_guide_eyebrow: "EVENT-GUIDE",
    cage_word: "Käfig",
    event_word: "Event",
    hero_banner_desc: "Empfohlene Sammelruf-Starter, Mitstreiter-Helden, Truppenverhältnisse und Strategie-Informationen für das Käfig-Event!",
    cage_core: "KÄFIG",
    section_kicker_guide: "EVENT-GUIDE",
    cage_event_title: "Käfig-Event",
    guide_panel_desc: "Wählen Sie unten Ihre verfügbaren Helden aus, um benutzerdefinierte Käfig-Teams zu erstellen und Ihre Truppenformationen zu optimieren.",
    cage_team_label: "KÄFIG-TEAM",
    rally_starter_team: "Sammelruf-Starter-Team",
    select_hero: "Held auswählen",
    select_hero_upper: "HELD AUSWÄHLEN",
    class_shooter: "SCHÜTZE",
    class_bomber: "BOMBER",
    class_shield: "SCHILD",
    label_shooter: "Schütze",
    label_bomber: "Bomber",
    label_shield: "Schild",
    troop_formation_title: "TRUPPENFORMATION",
    power_armor_7: "Power-Rüstung Nr. 07",
    power_armor_5: "Power-Rüstung Nr. 05",
    power_armor_4: "Power-Rüstung Nr. 04",
    stats_max: "STATISTIKEN(Max)",
    stat_shooter_atk: "Schützen ANG",
    stat_shooter_def: "Schützen VER",
    stat_bomber_atk: "Bomber ANG",
    robot_note_text: '"Phantom Cat (Power-Rüstung Nr. 07) ist derzeit die effektivste Power-Rüstung im Käfig-Event. Das Aktivieren von mehr Kernen maximiert das Potenzial der Kern-Fähigkeit direkt."',
    cage_event_upper: "KÄFIG-EVENT",
    joiner_heroes_title: "Mitstreiter-Helden (Verwenden Sie einen Helden pro Stufe)",
    tier_word: "STUFE",
    note_1: "Verwenden Sie nur Charaktere mit 4 Sternen oder höher, deren erste Kriegsfähigkeit auf Max/Level 5 ist.",
    note_2: "Passen Sie die ersten 4 Mitstreiter-Helden in Ihren eigenen Sammelrufen an.",
    note_3: "Gleiche Mitstreiter-Kriegsfähigkeiten sind nicht stapelbar.",
    event_strategy_upper: "EVENT-STRATEGIE",
    strategy_title: "Strategie",
    strategy_desc: "Strategie-Informationen werden hier hinzugefügt.",
    community_knowledge_upper: "COMMUNITY-WISSEN",
    tips_title: "Tipps & Hinweise",
    tips_desc: "Nützliche Tipps, getestete Formationen und Community-Notizen werden hier hinzugefügt."
  },

  // 5. TÜRKÇE (TR)
  tr: {
    hero_database: "Kahraman Veritabanı",
    nav_home: "Ana Sayfa",
    nav_heroes: "Kahramanlar",
    nav_events: "Etkinlikler",
    footer_text: "Resmi olmayan topluluk veritabanı - Sunucu #185 & #197 - el Fuego",
    community_db_title: "Topluluk Veritabanı",
    select_section: "Devam etmek için bir bölüm seçin",

    tome_kicker: "BİKİTAP",
    hero_kicker: "KAHRAMAN",
    equipment_kicker: "EKİPMAN",
    trove_kicker: "HAZİNE",

    armor_title: "Mahkûm Zırhı Yükseltme Gereksinimleri",
    equipment_title: "Ekipman Islah Gereksinimleri",
    trove_title: "Hazine Koleksiyonu Yükseltme Gereksinimleri",
    tome_upgrade_title: "Bikitap Yükseltme Gereksinimleri",
    troop_guide_title: "Birlik Rehberi ve Savaş Mekaniği",
    satellite_title: "Uydu Yükseltme Gereksinimleri",
    hero_equipment_title: "Kahramana Özel Ekipman Yükseltme Gereksinimleri",
    hero_star_title: "Kahraman Yıldız Yükseltme Gereksinimleri",

    card_cage_title: "Kafes Etkinliği",
    card_cage_desc: "Kafes etkinliği bilgileri.",
    card_armor_title: "Mahkûm Zırhı",
    card_armor_desc: "Mahkûm Zırhı seviye atlatma ve çekirdek yükseltme gereksinimleri.",
    card_trove_title: "Hazine Yükseltme",
    card_trove_desc: "Hazine yükseltme gereksinimleri.",
    card_tome_title: "Bikitap Yükseltme",
    card_tome_desc: "Bikitap yükseltme gereksinimleri.",
    card_troop_title: "Birlik Rehberi",
    card_troop_desc: "Birlik türleri, güçlü/zayıf yönler ve savaş mekanikleri.",
    card_satellite_title: "Uydu",
    card_satellite_desc: "Uydu bilgileri ve yükseltme rehberi.",
    card_equip_ref_title: "Kahraman Ekipman Islahı",
    card_equip_ref_desc: "Kahraman Ekipman Islahı yükseltme gereksinimleri.",
    card_hero_equip_title: "Kahramana Özel Ekipman",
    card_hero_equip_desc: "Kahramana özel ekipman bilgileri ve gereksinimleri.",
    card_hero_star_title: "Kahraman Yıldızı",
    card_hero_star_desc: "Kahraman yıldız yükseltme gereksinimleri.",

    event_guide_eyebrow: "ETKİNLİK REHBERİ",
    cage_word: "Kafes",
    event_word: "Etkinliği",
    hero_banner_desc: "Kafes Etkinliği için önerilen miting başlatıcı kahramanlar, katılan kahramanlar, birlik oranları ve strateji bilgileri!",
    cage_core: "KAFES",
    section_kicker_guide: "ETKİNLİK REHBERİ",
    cage_event_title: "Kafes Etkinliği",
    guide_panel_desc: "Özel Kafes Miting takımları oluşturmak ve birlik düzenlerinizi optimize etmek için aşağıdan mevcut kahramanlarınızı seçin.",
    cage_team_label: "KAFES TAKIMI",
    rally_starter_team: "Miting Başlatıcı Takım",
    select_hero: "Kahraman Seç",
    select_hero_upper: "KAHRAMAN SEÇ",
    class_shooter: "NİŞANCI",
    class_bomber: "BOMBACI",
    class_shield: "Kalkan",
    label_shooter: "Nişancı",
    label_bomber: "Bombacı",
    label_shield: "Kalkan",
    troop_formation_title: "BİRLİK DÜZENİ",
    power_armor_7: "Güç Zırhı No.07",
    power_armor_5: "Güç Zırhı No.05",
    power_armor_4: "Güç Zırhı No.04",
    stats_max: "İSTATİSTİKLER (Maks)",
    stat_shooter_atk: "Nişancı SLD",
    stat_shooter_def: "Nişancı SVN",
    stat_bomber_atk: "Bombacı SLD",
    robot_note_text: '"Phantom Cat (Güç Zırhı No.07) şu anda Kafes etkinliğindeki en etkili Güç Zırhıdır. Daha fazla Çekirdek etkinleştirmek, Çekirdek Becerisinin potansiyelini doğrudan en üst düzeye çıkaracaktır."',
    cage_event_upper: "KAFES ETKİNLİĞİ",
    joiner_heroes_title: "Katılan Kahramanlar (Her kademeden bir kahraman kullanın)",
    tier_word: "KADEME",
    note_1: "Yalnızca ilk savaş becerisi Maks/Seviye 5 olan 4 yıldızlı veya üzeri karakterleri kullanın.",
    note_2: "Kendi mitinglerinizdeki ilk 4 katılan kahramanı ayarlayın.",
    note_3: "Aynı katılan kahraman savaş becerileri üst üste birikmez.",
    event_strategy_upper: "ETKİNLİK STRATEJİSİ",
    strategy_title: "Strateji",
    strategy_desc: "Strateji bilgileri buraya eklenecektir.",
    community_knowledge_upper: "TOPLULUK BİLGİSİ",
    tips_title: "İpuçları ve Notlar",
    tips_desc: "Faydalı ipuçları, test edilmiş dizilimler ve topluluk notları buraya eklenecektir."
  }
};

/* =========================================================
   DİL DEĞİŞTİRME MEKANİZMASI
========================================================= */

function changeLanguage(lang) {
  // Seçilen dili tarayıcıya kaydet
  localStorage.setItem("selectedLanguage", lang);

  // Sayfadaki metinleri güncelle
  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.getAttribute("data-i18n");
    if (translations[lang] && translations[lang][key]) {
      if (translations[lang][key].includes("<")) {
        element.innerHTML = translations[lang][key];
      } else {
        element.textContent = translations[lang][key];
      }
    }
  });

  // Buton aktiflik durumlarını değiştir (sarı vurgu)
  document.querySelectorAll(".lang-btn").forEach((btn) => {
    if (btn.getAttribute("data-lang") === lang) {
      btn.classList.add("active");
    } else {
      btn.classList.remove("active");
    }
  });
}

// Sayfa yüklendiğinde dili çalıştır
document.addEventListener("DOMContentLoaded", () => {
  const savedLanguage = localStorage.getItem("selectedLanguage") || "en";
  changeLanguage(savedLanguage);
});