const TC_HEROES = [
  {name:'Alph', cls:'Bomber', eqTrigger:'solo_attack', eqStat:'ATK', eqValue:16, eqName:'', off:36.0, def:50.0, img:'assets/icons/alph.png'},
  {name:'Lanchester', cls:'Bomber', eqTrigger:'defending', eqStat:'DEF', eqValue:16, eqName:'Mech Ascension', off:30.0, def:61.0, img:'assets/icons/lanchester.png'},
  {name:'Koschevoi', cls:'Bomber', eqTrigger:'solo_attack', eqStat:'DEF', eqValue:16, eqName:'Surveillance Probe', off:30.0, def:16, img:'assets/icons/koschevoi.png'},
  {name:'Whisper', cls:'Bomber', eqTrigger:'rally_attack', eqStat:'Lethality', eqValue:16, eqName:'Nether Nectar', off:86.0, def:0, img:'assets/icons/whisper.png'},
  {name:'Wukong', cls:'Bomber', eqTrigger:'rally_attack', eqStat:'Lethality', eqValue:16, eqName:'Divine Power', off:41.0, def:0, img:'assets/icons/wukong.png'},
  {name:'Worrell', cls:'Bomber', eqTrigger:'solo_attack', eqStat:'ATK', eqValue:16, eqName:"Punisher's Grip", off:91.0, def:0, img:'assets/icons/worrell.png'},
  {name:'Ryuichi Ito', cls:'Bomber', eqTrigger:'rally_attack', eqStat:'ATK', eqValue:16, eqName:'Pinpoint Assault', off:16, def:0, img:'assets/icons/ryuichi-ito.png'},
  {name:'Lee', cls:'Bomber', eqTrigger:'defending', eqStat:'ATK', eqValue:16, eqName:'Careful Ambush', off:16, def:0, img:'assets/icons/lee.png'},
  {name:'Tyronn', cls:'Shield', eqTrigger:'rally_attack', eqStat:'ATK', eqValue:16, eqName:'Bull Rush', off:41.0, def:0, img:'assets/icons/tyronn.png'},
  {name:'Zoltan', cls:'Shield', eqTrigger:'defending', eqStat:'DEF', eqValue:16, eqName:'Redemption Shield', off:100.0, def:16, img:'assets/icons/zoltan.png'},
  {name:'Caesar', cls:'Shield', eqTrigger:'defending', eqStat:'ATK', eqValue:16, eqName:"Avenger's Fury", off:36.0, def:25.0, img:'assets/icons/caesar.png'},
  {name:'Marcus', cls:'Shield', eqTrigger:'defending', eqStat:'HP', eqValue:16, eqName:'Flesh Revival', off:25.0, def:16, img:'assets/icons/marcus.png'},
  {name:'Otto', cls:'Shield', eqTrigger:'defending', eqStat:'DEF', eqValue:16, eqName:'Entrenched Position', off:75.0, def:16, img:'assets/icons/otto.png'},
  {name:'Xuanming', cls:'Shield', eqTrigger:'defending', eqStat:'ATK', eqValue:16, eqName:'Qimen Formation', off:41.0, def:25.0, img:'assets/icons/xuanming.png'},
  {name:'Phoenix', cls:'Shield', eqTrigger:'solo_attack', eqStat:'HP', eqValue:16, eqName:'Colossus Hammer', off:25.0, def:41.0, img:'assets/icons/phoenix.png'},
  {name:'Mireya', cls:'Shooter', eqTrigger:'rally_attack', eqStat:'Lethality', eqValue:16, eqName:'Whispering Death', off:61.0, def:20.0, img:'assets/icons/mireya.png'},
  {name:'Drake', cls:'Shooter', eqTrigger:'defending', eqStat:'Lethality', eqValue:16, eqName:'Break Out', off:30.0, def:40.0, img:'assets/icons/drake.png'},
  {name:'Sawyer', cls:'Shooter', eqTrigger:'rally_attack', eqStat:'HP', eqValue:16, eqName:'Howling Engine', off:45.0, def:41.0, img:'assets/icons/sawyer.png'},
  {name:'Edwin', cls:'Shooter', eqTrigger:'solo_attack', eqStat:'HP', eqValue:16, eqName:'Resolute Heart', off:0, def:16, img:'assets/icons/edwin.png'},
  {name:'Kate', cls:'Shooter', eqTrigger:'defending', eqStat:'Lethality', eqValue:16, eqName:'Home Advantage', off:41.0, def:0, img:'assets/icons/kate.png'},
  {name:'Ada', cls:'Shooter', eqTrigger:'rally_attack', eqStat:'ATK', eqValue:16, eqName:'Firearm Mastery', off:26.0, def:0, img:'assets/icons/ada.png'},
  {name:'Veronica', cls:'Shooter', eqTrigger:'solo_attack', eqStat:'Lethality', eqValue:16, eqName:'Scarlet Pursuit', off:41.0, def:25.0, img:'assets/icons/veronica.png'},
];
